#include "header.hpp"

int main()
{
    //Part A
    Card *card4 = new Card(DOUBLEARROWBOTTOM, SINGLETRIANGLEBOTTOM, DOUBLETRIANGLETOP, SINGLEARROWTOP, 4);
    Card *card5 = new Card(DOUBLETRIANGLEBOTTOM, SINGLEARROWBOTTOM, DOUBLETRIANGLETOP, SINGLETRIANGLETOP, 5);
    Card *card6 = new Card(DOUBLETRIANGLETOP, DOUBLEARROWTOP, SINGLEARROWBOTTOM, DOUBLETRIANGLEBOTTOM, 6);
    Card *card7 = new Card(DOUBLETRIANGLEBOTTOM, DOUBLEARROWTOP, DOUBLETRIANGLETOP, SINGLEARROWBOTTOM, 7);

    std::vector<Card*> args;
    args.push_back(card4);
    args.push_back(card5);
    args.push_back(card6);
    args.push_back(card7);


    Grid *partAGrid = new Grid(args, 2);

    partAGrid->print();



    //Part B

    //Clean up Part A cards since they are passed by reference
    delete card4;
    delete card5;
    delete card6;
    delete card7;

    Card *card1 = new Card(SINGLEARROWBOTTOM, DOUBLETRIANGLETOP, SINGLETRIANGLETOP, DOUBLEARROWBOTTOM, 1);
    Card *card2 = new Card(DOUBLEARROWBOTTOM, SINGLETRIANGLEBOTTOM, DOUBLEARROWTOP, SINGLEARROWTOP, 2);
    Card *card3 = new Card(DOUBLEARROWBOTTOM, SINGLETRIANGLEBOTTOM, DOUBLETRIANGLETOP, SINGLEARROWTOP, 4);
    Card *card4 = new Card(DOUBLEARROWBOTTOM, SINGLETRIANGLEBOTTOM, DOUBLETRIANGLETOP, SINGLEARROWTOP, 4);
    Card *card5 = new Card(DOUBLETRIANGLEBOTTOM, SINGLEARROWBOTTOM, DOUBLETRIANGLETOP, SINGLETRIANGLETOP, 5);
    Card *card6 = new Card(DOUBLETRIANGLETOP, DOUBLEARROWTOP, SINGLEARROWBOTTOM, DOUBLETRIANGLEBOTTOM, 6);
    Card *card7 = new Card(DOUBLETRIANGLEBOTTOM, DOUBLEARROWTOP, DOUBLETRIANGLETOP, SINGLEARROWBOTTOM, 7);
    Card *card8 = new Card(SINGLETRIANGLETOP, DOUBLEARROWTOP, SINGLETRIANGLETOP, SINGLEARROWBOTTOM, 8);
    Card *card9 = new Card(SINGLEARROWBOTTOM, DOUBLEARROWTOP, DOUBLETRIANGLETOP, SINGLETRIANGLEBOTTOM, 7);





    
}